### PR TITLE
Resolve memory leaks, fixes #1

### LINKED ISSUE #1: Fix memory leaks
As described [here](https://en.delphipraxis.net/topic/11579-how-to-debug-a-not-responding-program-element/?page=2&tab=comments#comment-92166) when running SupperLemmix in Debug mode, a lot of memory leaks are reported.

FastMM can provide call stacks where these leaks were allocated, details are outlined in https://stackoverflow.com/a/1130506/386473

I created this issue since I plan to make a pull request to fix these leaks

### PR DESCRIPTION
**Pull request by modersohn**
* most were simply forgotten to be freed
* but TLemmixHotkeyManager.LoadFile was missing a try/finally since the method might Exit early, also so it is freed in case of an exception

### CODE REVIEW

**Comment by modersohn** [comment]
It is much easier to view the changes if you hide whitespace - which looks like this:

image

**Review by andersmelander — APPROVED** [review]
Looks good

**Comment by Willicious** [comment]
Thanks for doing this! I'll get the changes pulled across to working copy and test them out 🚀

**Comment by Willicious** [comment]
Brilliant work! It's great to not see that list of leaks any more! From here on out, I'll make sure to free everything properly

**Pull request merged**
